version: "3"
services:
    fish-db:
        image: fish-db
        container_name: fish-db
        build: ./db
        environment:
            - PGDATA=/postgresdata
        volumes:
            - ./db/data:/postgresdata
    fish-node:
        image: fish-node
        container_name: fish-node
        build: ./node
        volumes: 
            - ./node:/srv/node
        environment:
            - BASE_URL=${BASE_URL}
            - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
            - FACEBOOK_API_VERSION=${FACEBOOK_API_VERSION}
            - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
            - STATIC_SERVER=${STATIC_SERVER}
            - BUILD_ENV=${BUILD_ENV}
            - PROTOCOL=http://
        depends_on:
            - fish-db
    fish-proxy:
        image: fish-proxy
        container_name: fish-proxy
        build: ./proxy
        ports:
            - "80:80"
        volumes:
            - ./proxy:/site-base-config
        environment:
            - BASE_URL=${BASE_URL}
            - STATIC_SERVER=${STATIC_SERVER}
        depends_on:
            - fish-node
